-- good boy sql
CREATE TABLE test1 (
  thing VARCHAR(255) NOT NULL
);

-- bad boy sql
GET OFF MY LAWN YOU DAMN KIDS SKATING ON THE SIDEWALKS YOU WOULDNT KNOW GOOD SQL IF IT SLID INTO YOUR DMS WITH A DANK MEME;